services:
    app.handler.pathfinder.lines:
        class: AppBundle\Handler\Pathfinder\Linefinder
        arguments: ['@app.helper.input.factory', '@app.model.manager']

    app.helper.input.factory:
        class: AppBundle\Helper\InputParser\Factory
        arguments: ['@app.model.manager']

    app.model.manager:
        class: AppBundle\Model\Manager
        arguments: []
